[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[[services]]
name = "ffmpeg-video-api"

[build.nixpacksConfigOverride]
providers = ["python", "ffmpeg"]

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"
